# Generated by Django 5.1.1 on 2024-12-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('cash_registers', models.PositiveIntegerField(verbose_name='Количество касс')),
                ('capacity', models.PositiveIntegerField(verbose_name='Товароёмкость')),
                ('work_mode', models.CharField(choices=[('24/7', 'Круглосуточно'), ('9-18', 'С 9:00 до 18:00'), ('10-20', 'С 10:00 до 20:00')], default='9-18', max_length=10, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Аптека',
                'verbose_name_plural': 'Аптеки',
            },
        ),
    ]
