# Generated by Django 5.1.1 on 2024-12-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='facade_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy_photos/', verbose_name='Фотография фасада'),
        ),
    ]
